2023-08-04 23:44:31,473 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:44:36,817 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:44:42,161 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:44:47,489 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:45:04,786 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:45:10,114 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:45:15,458 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:45:20,786 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:45:51,270 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
2023-08-04 23:45:56,614 ERROR: Exception on / [POST] [in c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1506, in finalize_request
    response = self.make_response(rv)
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'index' did not return a valid response. The function either returned None or ended without a return statement.
